import '@/styles/globals.css';
import { NavBar } from '@/components/nav-bar';
import { League_Spartan as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={cn('flex flex-col font-sans', fontSans.variable)}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

