import { cn } from '@/lib/utils';
import '../styles/globals.css';
import { League_Spartan } from 'next/font/google';
import { NavBar } from '@/components/nav-bar';
import { FlexBoxColumn } from '@/components/ui/flexbox-column';

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('flex flex-col', leagueSpartan.className)}>
        <NavBar />
        <FlexBoxColumn className='items-center px-6 py-8'>{children}</FlexBoxColumn>
      </body>
    </html>
  );
}

